apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-simple-db-deployment
  labels:
    app: docker-simple-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-simple-db
  template:
    metadata:
      labels:
        app: docker-simple-db
    spec:
      containers:
      - name: docker-simple-db
        image: docker-simple-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        

